name: iOS Tests

on:
  push:
    branches:
      - develop-iosadv
  pull_request:
    branches:
      - develop-iosadv

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1

      - name: Install dependencies
        run: |
          xcodebuild -resolvePackageDependencies

      - name: Run tests
        run: |
          xcodebuild test \
            -scheme Test \
            -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=17.2' \
            -derivedDataPath build
